version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-dashboard.address=:8080"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Expose dashboard securely
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.traefik.rule=Host(`traefik.tahaidrissi.digital`)"
        - "traefik.http.routers.traefik.entrypoints=web-dashboard"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=authtraefik"
        - "traefik.http.middlewares.authtraefik.basicauth.users=admin:{SHA}OwBKxtimAmgfXuNYfJJIVWeeIdk="
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
networks:
  public:
    external: true
