version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public
      - --entrypoints.web.address=:80      # HTTP only
      - --entrypoints.web-dashboard.address=:8080
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [public]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        # Dashboard via chemin (évite les soucis DNS)
        - traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard`)
        - traefik.http.routers.dashboard.entrypoints=web-dashboard
        - traefik.http.services.dashboard.loadbalancer.server.port=8080

networks:
  public:
    external: true
